// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
// / await Firebase.initializeApp(
// /   options: DefaultFirebaseOptions.currentPlatform,
// / );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVexxlfnQrBCpFwHdNwDLgGsi__b7OjB0',
    appId: '1:343984419001:web:4cdb19018845b0e645ab68',
    messagingSenderId: '343984419001',
    projectId: 'loginzomato-98ab9',
    authDomain: 'loginzomato-98ab9.firebaseapp.com',
    storageBucket: 'loginzomato-98ab9.appspot.com',
    measurementId: 'G-DYE95FNZGF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEHzUnyFW2RS0Um8NAnakPqmbJpaE989Y',
    appId: '1:343984419001:android:99c043b97581991b45ab68',
    messagingSenderId: '343984419001',
    projectId: 'loginzomato-98ab9',
    storageBucket: 'loginzomato-98ab9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9Pccf-KjSsw3uzQm2B7MA_vngr7rV0QE',
    appId: '1:343984419001:ios:760de4d229dd5b6c45ab68',
    messagingSenderId: '343984419001',
    projectId: 'loginzomato-98ab9',
    storageBucket: 'loginzomato-98ab9.appspot.com',
    iosBundleId: 'com.example.zomato',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9Pccf-KjSsw3uzQm2B7MA_vngr7rV0QE',
    appId: '1:343984419001:ios:760de4d229dd5b6c45ab68',
    messagingSenderId: '343984419001',
    projectId: 'loginzomato-98ab9',
    storageBucket: 'loginzomato-98ab9.appspot.com',
    iosBundleId: 'com.example.zomato',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDVexxlfnQrBCpFwHdNwDLgGsi__b7OjB0',
    appId: '1:343984419001:web:ef8e084100acec5f45ab68',
    messagingSenderId: '343984419001',
    projectId: 'loginzomato-98ab9',
    authDomain: 'loginzomato-98ab9.firebaseapp.com',
    storageBucket: 'loginzomato-98ab9.appspot.com',
    measurementId: 'G-MYVZF7CFFG',
  );
}
